/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package applicationForm;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import connect_database.MySQLConnect;
import includeClass.BrandItem;
import includeClass.CategoryItem;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

/**
 *
 * @author user
 */
public class PanelProduct extends javax.swing.JPanel {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public PanelProduct() {
        initComponents();
        txtSearch.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "ຄົ້ນຫາ");
        txtSearch.putClientProperty(FlatClientProperties.TEXT_FIELD_TRAILING_ICON, new FlatSVGIcon("image_svg/search.svg"));
        
        //ປ່ຽນສີພື້ນຫົວຕາຕະລາງ
        JTableHeader header = jTable1.getTableHeader();
        header.setFont(new Font("Lao_SomVang", Font.PLAIN, 14));
        header.setOpaque(false);
        header.setBackground(new Color(108, 117, 125));
        header.setForeground(new Color(243, 243, 243));

        //ສະແດງຜົນຢູ່ກາງຖັນ
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        jTable1.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        jTable1.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        jTable1.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        jTable1.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
        jTable1.getColumnModel().getColumn(9).setCellRenderer(centerRenderer);

        //ສະແດງຜົນຢູ່ດ້ານຂວາຖັນ
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        jTable1.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
        jTable1.getColumnModel().getColumn(6).setCellRenderer(rightRenderer);

        //ເສັ້ນຕາຕະລາງ
        jTable1.setShowGrid(false);
        jTable1.setShowHorizontalLines(true);
        jTable1.setShowVerticalLines(true);
        jTable1.setGridColor(new Color(139, 138, 137));
        
        //ເຊື່ອມຕໍ່ຖານຂໍ້ມູນ
        conn = MySQLConnect.connectDB();
        brand();
        category();
        
    }
        //ສ້າງເມທອດສະແດງຊື່ຍີ່ຫໍ້ txtBrand
        private void brand(){
            try {
                String sql = "SELECT * FROM brand Order by brand_name ASC";
                pst = conn .prepareStatement (sql);
                 rs = pst.executeQuery();
                 while(rs.next()){
                     txtBrand.addItem(new BrandItem (rs.getString(1),  rs.getString(2)));
                 }

            } catch (Exception e) {
                 JOptionPane.showMessageDialog(null, e);
            }
        }
        
        //ສ້າງເມທອດສະແດງຊື່ຍີ່ຫໍ້ txtCategory
        private void category() {
            try {
                String sql = "SELECT * FROM category Order by category_name ASC";
                pst = conn .prepareStatement (sql);
                 rs = pst.executeQuery();
                 while(rs.next()){
                     txtCategory.addItem(new CategoryItem (rs.getString(1),  rs.getString(2)));
                 }

            } catch (Exception e) {
                 JOptionPane.showMessageDialog(null, e);
            }
        }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtBarcode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtQuantity_min = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtProduct_name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCost_price = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtUnit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtRetail_price = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtQuantit = new javax.swing.JTextField();
        txtBrand = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        txtCategory = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1290, 543));

        jTable1.setFont(new java.awt.Font("Lao_SomVang", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ລະຫັດບາໂຄ້ດ", "ລາຍການສິນຄ້າ", "ຫົວໜ່ວຍ", "ຈໍານວນ", "ຈໍານວນຕໍ່າສຸດ", "ລາຄາຕົ້ນທືນ", " ລາຄາຂາຍ", "ຍີ່ຫໍ້", "ປະເພດ", "ສະຖານະ"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ຈັດການຂໍ້ມູນສິນຄ້າ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lao_SomVang", 0, 16))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lao_SomVang", 0, 14)); // NOI18N
        jLabel2.setText("ລະຫັດບາໂຄ້ດ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtBarcode.setFont(new java.awt.Font("Lao_SomVang", 0, 14)); // NOI18N
        txtBarcode.setName(""); // NOI18N
        jPanel2.add(txtBarcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 240, -1));

        jLabel3.setFont(new java.awt.Font("Lao_SomVang", 0, 14)); // NOI18N
        jLabel3.setText("ຈຳນວນຕ່ຳສຸດ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        txtQuantity_min.setFont(new java.awt.Font("Lao_SomVang", 0, 14)); // NOI18N
        jPanel2.add(txtQuantity_min, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 240, -1));

        jLabel4.setFont(new java.awt.Font("Lao_SomVang", 0, 14)); // NOI18N
        jLabel4.setText("ຍີ່ຫໍ້ສິນຄ້າ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lao_SomVang", 0, 14)); // NOI18N
        jLabel5.setText("ລາຍການສິນຄ້າ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtProduct_name.setFont(new java.awt.Font("Lao_SomVang", 0, 14)); // NOI18N
        jPanel2.add(txtProduct_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 240, -1));

        jLabel6.setFont(new java.awt.Font("Lao_SomVang", 0, 14)); // NOI18N
        jLabel6.setText("ລາຄາຕົ້ນທືນ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        txtCost_price.setFont(new java.awt.Font("Lao_SomVang", 0, 14)); // NOI18N
        jPanel2.add(txtCost_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 240, -1));

        jLabel7.setFont(new java.awt.Font("Lao_SomVang", 0, 14)); // NOI18N
        jLabel7.setText("ຫົວຫນ່ວຍ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        txtUnit.setFont(new java.awt.Font("Lao_SomVang", 0, 14)); // NOI18N
        jPanel2.add(txtUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 240, -1));

        jLabel8.setFont(new java.awt.Font("Lao_SomVang", 0, 14)); // NOI18N
        jLabel8.setText("ລາຄາຂາຍ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        txtRetail_price.setFont(new java.awt.Font("Lao_SomVang", 0, 14)); // NOI18N
        jPanel2.add(txtRetail_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 240, -1));

        jLabel9.setFont(new java.awt.Font("Lao_SomVang", 0, 14)); // NOI18N
        jLabel9.setText("ຍີ່ຫໍ້ສິນຄ້າ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        txtQuantit.setFont(new java.awt.Font("Lao_SomVang", 0, 14)); // NOI18N
        jPanel2.add(txtQuantit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 240, -1));

        txtBrand.setFont(new java.awt.Font("Lao_SomVang", 0, 14)); // NOI18N
        jPanel2.add(txtBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, 240, -1));

        jLabel10.setFont(new java.awt.Font("Lao_SomVang", 0, 14)); // NOI18N
        jLabel10.setText("ປະເພດສິນຄ້າ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, -1, -1));

        txtCategory.setFont(new java.awt.Font("Lao_SomVang", 0, 14)); // NOI18N
        jPanel2.add(txtCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 240, -1));

        jLabel11.setFont(new java.awt.Font("Lao_SomVang", 0, 14)); // NOI18N
        jLabel11.setText("ສະຖານະ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, -1, -1));

        txtStatus.setFont(new java.awt.Font("Lao_SomVang", 0, 14)); // NOI18N
        txtStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ມີ", "ບໍ່ມີ" }));
        jPanel2.add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, 240, -1));

        btnAdd.setBackground(new java.awt.Color(11, 94, 215));
        btnAdd.setFont(new java.awt.Font("Lao_SomVang", 0, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(251, 238, 230));
        btnAdd.setText("ເພີ່ມ");
        jPanel2.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 70, -1));

        btnEdit.setBackground(new java.awt.Color(255, 201, 12));
        btnEdit.setFont(new java.awt.Font("Lao_SomVang", 0, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(28, 31, 35));
        btnEdit.setText("ແກ້ໄຂ");
        jPanel2.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 70, -1));

        btnDelete.setBackground(new java.awt.Color(187, 45, 59));
        btnDelete.setFont(new java.awt.Font("Lao_SomVang", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(253, 254, 254));
        btnDelete.setText("ລືບ");
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 70, -1));

        btnCancel.setBackground(new java.awt.Color(21, 115, 71));
        btnCancel.setFont(new java.awt.Font("Lao_SomVang", 0, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(253, 254, 254));
        btnCancel.setText("ຍົກເລີກ");
        btnCancel.setMargin(new java.awt.Insets(2, 3, 3, 3));
        jPanel2.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 70, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1090, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        txtSearch.setFont(new java.awt.Font("Lao_SomVang", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1230, Short.MAX_VALUE))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addGap(55, 55, 55))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBarcode;
    private javax.swing.JComboBox txtBrand;
    private javax.swing.JComboBox txtCategory;
    private javax.swing.JTextField txtCost_price;
    private javax.swing.JTextField txtProduct_name;
    private javax.swing.JTextField txtQuantit;
    private javax.swing.JTextField txtQuantity_min;
    private javax.swing.JTextField txtRetail_price;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JComboBox<String> txtStatus;
    private javax.swing.JTextField txtUnit;
    // End of variables declaration//GEN-END:variables
}
